# Generated by Django 4.2 on 2023-04-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
