# Generated by Django 4.2 on 2023-04-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_double_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='double_comment',
            name='post',
        ),
        migrations.AddField(
            model_name='double_comment',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='double_comments', to='app.comment'),
            preserve_default=False,
        ),
    ]
